const importColumns = [
    {
      row: [
        {
          id: "srNo",
          numeric: true,
          minWidth: 80,
          isSortable: true,
          default: true,
          label: "S.No",
        }, //flexGrow:1
        {
          id: "jobNo",
          numeric: false,
          minWidth: 90,
          isSortable: false,
          default: true,
          display: false,
          label: "Job No",
          sticky: true,
          flexGrow: 1,
        },
        {
          id: "jobCreationDate",
          numeric: false,
          minWidth: 90,
          isSortable: true,
          default: true,
          display: false,
          label: "Job Date & Time",
          filter: true,
          flexGrow: 1,
        },
        {
          id: "transactionRefNo",
          numeric: false,
          minWidth: 90,
          isSortable: false,
          default: true,
          display: true,
          label: "Reference No.",
          flexGrow: 1,
        },
        {
          id: "consigneeName",
          numeric: false,
          minWidth: 90,
          isSortable: false,
          default: true,
          display: true,
          label: "Importer",
          filter: true,
          flexGrow: 1,
        },
        {
          id: "shipperName",
          numeric: false,
          minWidth: 90,
          isSortable: false,
          default: true,
          display: true,
          label: "Supplier",
          filter: true,
          flexGrow: 1,
        },
        {
          id: "cbBranch",
          numeric: false,
          minWidth: 90,
          isSortable: false,
          default: true,
          display: true,
          label: "CB Branch",
          filter: true,
          flexGrow: 1,
        },
        {
          id: "status",
          numeric: false,
          minWidth: 90,
          isSortable: true,
          default: true,
          display: true,
          label: "Status",
          filter: true,
          flexGrow: 1,
        },
        {
          id: "createdBy",
          numeric: false,
          minWidth: 90,
          isSortable: true,
          default: true,
          display: true,
          label: "Assigned To",
          filter: true,
          flexGrow: 1,
        },
      ],
    },
    {
      row: [
        {
          id: "23456789",
          numeric: true,
          minWidth: 80,
          isSortable: true,
          default: true,
          label: "",
        },
        {
          id: "FromAddress",
          numeric: false,
          minWidth: 180,
          isSortable: false,
          default: true,
          display: false,
          label: "From Address",
          sticky: true,
          flexGrow: 2,
        },
        {
          id: "ToAddress",
          display: true,
          isSortable: false,
          default: true,
          minWidth: 90,
          label: "To Address",
          flexGrow: 1,
          left: "7px",
        }, //left:'0.6%'
        {
          id: "email",
          numeric: false,
          minWidth: 270,
          isSortable: false,
          default: true,
          display: true,
          label: "EmailSubjectLine",
          flexGrow: 3,
          left: "-5.2px",
        }, //left:'-0.4%'
        {
          id: "update",
          numeric: false,
          minWidth: 90,
          isSortable: true,
          default: true,
          display: true,
          label: "Created By",
          flexGrow: 1,
          left: "23px",
          filter: true,
        },
        {
          id: "time",
          display: true,
          isSortable: false,
          default: true,
          minWidth: 90,
          label: "Updated By",
          flexGrow: 1,
          left: "12px",
          filter: true,
        },
      ],
    },
    {
      row: [
        {
          id: "",
          display: true,
          isSortable: false,
          default: true,
          minWidth: 80,
          label: "",
        },
        {
          id: "a",
          display: true,
          isSortable: false,
          default: true,
          minWidth: 90,
          label: "Updated Date& Time",
          flexGrow: 1,
        },
        {
          id: "customsHouseCode",
          display: true,
          isSortable: false,
          default: true,
          minWidth: 90,
          label: "Port Of Loading",
          flexGrow: 1,
          filter: true,
        },
        {
          id: "beSbNo",
          numeric: false,
          minWidth: 90,
          isSortable: false,
          default: true,
          display: true,
          label: "Custom House Code",
          flexGrow: 1,
          filter: true,
        },
        {
          id: "beSbDate",
          numeric: false,
          minWidth: 90,
          isSortable: false,
          default: true,
          display: true,
          label: "BE Number",
          flexGrow: 1,
          filter: true,
        },
        {
          id: "beSbType",
          numeric: false,
          minWidth: 90,
          isSortable: false,
          default: true,
          display: true,
          label: "BE Date",
          flexGrow: 1,
          filter: true,
        },
        {
          id: "jobInvFobValue",
          numeric: false,
          minWidth: 90,
          isSortable: true,
          default: true,
          display: true,
          label: "BE Type",
          flexGrow: 1,
        },
        {
          id: "dutyPayable",
          numeric: false,
          minWidth: 90,
          isSortable: true,
          default: true,
          display: true,
          label: "Assesable Value",
          flexGrow: 1,
        },
        {
          id: "",
          display: true,
          isSortable: false,
          default: true,
          minWidth: 90,
          label: "Duty Payable",
          flexGrow: 1,
        },
      ],
    },
  ];

export default importColumns

